### ISSUE TITLE
can't see the figures referenced in Elliptical Orbit Correction

### ISSUE THREAD

**Issue by daveoloughlin** [samsammurphy/6S_LUT#10]
https://github.com/samsammurphy/6S_LUT/raw/master/table_elliptical_correction.png and https://github.com/samsammurphy/6S_LUT/raw/master/harmonic_function.png.

**Comment by samsammurphy** [comment]
Thanks Dave! Will put up fresh links on Monday.

**Comment by samsammurphy** [comment]
Ok, now using links hosted by www.imgur.com, I think that should resolve it.
