### ISSUE TITLE
aerosol model guidance

### ISSUE THREAD

**Issue by samsammurphy** [samsammurphy/6S_LUT#12]
some guidance in choosing an aerosol_profile would be useful, for me at least. I assume CO is just the "default". DE and MA seem pretty self explanatory? When would you prefer NO? UR would be used for NYC? Raleigh?

**Comment by samsammurphy** [comment]
I added a brief wiki on aerosol models, was not sure how best to link it to the rest of the documentation. do you have any ideas? @daveoloughlin

**Comment by samsammurphy** [comment]
p.s. the NO aerosol model might not be for practical applications. thanks for asking the question. I have actually removed it from the 'standard' LUTs included in this repo because this.

**Comment by daveoloughlin** [comment]
The "Can I make my own iLUTs 
<https://github.com/samsammurphy/6S_LUT/wiki/Interpolated-Look-up-Tables-%28iLUTs%29#can-i-make-my-own-iluts>?" 
section of the iLUTs page is what sparked the question. I think the 
information fits well in to the "How does it work"/Atmospheric 
Correction example discussion. To me, it would fit best as an asterisk, 
link, or footnote to the "Can I make my own iLUTs" question, as in why 
would I want to.
I like your description, by the way. It had not occurred to me that 
LEDAPS is always using the continental model. Thanks.

**Comment by samsammurphy** [comment]
Thanks :+1: 
Have added links to aerosol model wiki in iLUTs page (can I make my own iLUTs?) and to the jupyter notebook example for atmospheric correction.
